version: '3.8'
services:
  # PostgreSQL database service
  db:
    image: postgres:15
    container_name: bancocentral-db
    environment:
      POSTGRES_DB: bancocentral     # Name of the database
      POSTGRES_USER: postgres       # Database user
      POSTGRES_PASSWORD: root       # User password
    volumes:
      - postgres-data:/var/lib/postgresql/data   # Mount a volume for data persistence
    ports:
      - "5432:5432"

  # Spring Boot application service
  app:
    build: .
    container_name: bancocentral-app
    depends_on:
      - db   # Ensures the 'db' service starts first
    ports:
      - "8080:8080"
    environment:
      # Credentials MUST match those of the 'db' service
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bancocentral
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres-data:
